# Generated by Django 3.0.8 on 2022-06-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="name",
            field=models.TextField(default="Lunch"),
        ),
    ]
